login:
  password: password
  username: admin
pipelines:
  - - echo
  - - json
    - ip
    - user-agent
  - - headers
    - post
base: https://httpbin.org/
tests:
  echo:
    request:
      method: get
      uri: http://echo.drink.cafe/echo
      files: # http://docs.python-requests.org/en/master/user/advanced/#post-multiple-multipart-encoded-files
        - - form_field_name
          - - the file name
            - "read:example.yml"
            - "text/plain"
      query:
        pwd: "{self.env.PWD}"
      auth:
        - user
        - pass
      cookies:
        - name: Cookie-One
          value: hello world
          domain: "{self.base}"
        - name: Cookie-2
          value: hello world
          domain: "{self.base}"
    response:
      - status: 200
        debug:
          - body
  json:
    request:
      method: get
      uri: /json
    response:
      - status: 200
        body:
          slideshow.slides[0].title: Wake up to WonderWidgets!
        debug:
          - body
  headers:
    request:
      uri: /headers
      headers:
        X-DATA-A: "{self.tests.json.results.200.json.slideshow.title}"
        X-DATA-B: "file: ./data/header.txt"
    response:
      - status: 200
        body:
          headers['X-Data-A']: "{self.tests.json.results.200.json.slideshow.title}"
        debug:
          - body
  ip:
    request:
      method: get
      uri: /ip
    response:
      - status: 200
        body:
          path.path.path1: 3
          path.path2.path3: 4
        stop: false
        debug:
          - body
  user-agent:
    request:
      method: get
      uri: /user-agent
      headers:
        User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
    response:
      - status: 200
        next:
          id: baidu
        debug:
          - body
  baidu:
    request:
      method: get
      uri: https://www.baidu.com
      timeout: 3
    response:
      - status: 200
        debug:
          - headers
  post:
    request:
      method: post
      uri: /post
      body:
        data: "json: ./data/body.json"
    response:
      - status: 200
        debug:
          - body

